apiVersion: v1
kind: ConfigMap
metadata:
  name: v2v-job-source
data:
  ova: |
    dsl.ova
---
apiVersion: v1
kind: Pod
metadata:
  name: j
spec:
  restartPolicy: Never
  containers:
  - name: vocker
    image: quay.io/fabiand/vocker
    command: ["/usr/bin/sleep", "inf"]
    volumeMounts:
    - name: source
      mountPath: /v2v-src
    - name: target
      mountPath: /v2v-dst
  volumes:
  - name: source
    configMap:
      name: v2v-job-source
  - name: target
    emptyDir: {}
