apiVersion: batch/v1
kind: Job
metadata:
  name: v2v-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: v2v
        image: quay.io/fabiand/v2v-job
        env:
        - name: V2V_SRC
          value: "disk /v2v-src/disk.raw"
        securityContext:
          privileged: true
        volumeMounts:
        - name: kvm
          mountPath: /dev/kvm
      volumes:
      - name: kvm
        hostPath:
          path: /dev/kvm
          type: CharDevice
  backoffLimit: 3
