apiVersion: batch/v1
kind: Job
metadata:
  name: v2v-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: v2v
        image: quay.io/fabiand/v2v-job
        args: ["/v2v-dst", "disk", "example"]
        env:
        - name: DEBUG
          value: 1
        securityContext:
          privileged: true
        volumeMounts:
        - name: dst
          mountPath: /v2v-dst
#        - name: kvm
#          mountPath: /dev/kvm
      volumes:
      - name: dst
        emptyDir: {}
#      - name: kvm
#        hostPath:
#          path: /dev/kvm
#          type: CharDevice
  backoffLimit: 3
