apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: v2v-job-mounts
spec:
  selector:
    matchLabels:
      role: v2v-job
  volumeMounts:
  - name: source
    mountPath: /v2v-src
  - name: target
    mountPath: /v2v-dst
  volumes:
  - name: source
    configMap:
      name: v2v-job-source
  - name: target
    emptyDir: {}
#   persistentVolumeClaim:
#   claimName: vocker-images
# - name: cache # would be an improvement
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: v2v-job-source
data:
  ova:
  libvirt:
---
apiVersion: batch/v1
kind: Job
metadata:
  name: v2v-job
spec:
  template:
    metadata:
      labels:
        role: v2v-job
    spec:
      restartPolicy: Never
      containers:
      - name: v2v
        image: quay.io/fabiand/v2v-job
  backoffLimit: 4
